name: Lint

on:
  pull_request:
    branches: [ main ]


jobs:
    lint-code:
      name: lint java code
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java SDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Allow gradlew to execute
        run: chmod +x gradlew

      - name: Lint with gradle
        run: ./gradlew lint
        continue-on-error: false