name: Format

on:
  pull_request:
    branches: [ main ]

jobs:
  format-code:
    name: format java code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true

      - name: Print diffs
        run: git --no-pager diff